## L1 Vector Norm
- Manhatten Distance from origin

In [1]:
# l1 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


## L2 Vector Norm
- Euclidean Distance

In [2]:
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


- Methods of regularization
## Max Norm
- Max value of the vector

In [3]:
from numpy import inf
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0
